FROM ubuntu
MAINTAINER hsh "hsh.0223.ok@163.com"

ENV DEBIAN_FRONTEND noninteractive
#install mysql-server
RUN apt-get install -y mysql-server
#config mysql-server
RUN service mysql start &&\
 mysql -e "grant all privileges on *.* to 'root'@'%' identified by 'root';" &&\
 mysql -e "grant all privileges on *.* to 'root'@'localhost' identified by 'root';" &&\
 mysql -u root -proot -e "show databases;"

#external host can connect to container
ADD my.cnf /etc/mysql/my.cnf

#VOLUME ["/var/lib/mysql"]
EXPOSE 3306

CMD ["/usr/bin/mysqld_safe"]  

